### ISSUE TITLE
Error on training phase

### ISSUE THREAD

**Issue by alex-eurec** [p-sodmann/Spacy3Textcat#1]
Hello.

Thanks for the tutorial. You clearly explain what to do and give actionable tools and script to test it.

In fact, I am testing the scripts, and I run into a problem. I followed your instructions:
```bash
git clone https://github.com/p-sodmann/Spacy3Textcat.git
cd Spacy3Textcat/
mkdir data
python create_data.py
python -m spacy train config.cfg --output ./output
```

Then, the output of the last command is:
```
✔ Created output directory: output
ℹ Using CPU

=========================== Initializing pipeline ===========================
[2021-03-29 15:13:38,550] [INFO] Set up nlp object from config
[2021-03-29 15:13:38,560] [INFO] Pipeline: ['tok2vec', 'textcat']
[2021-03-29 15:13:38,564] [INFO] Created vocabulary
[2021-03-29 15:13:38,564] [INFO] Finished initializing nlp object
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/cli/_util.py", line 69, in setup_cli
    command(prog_name=COMMAND)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/cli/train.py", line 56, in train_cli
    nlp = init_nlp(config, use_gpu=use_gpu)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/training/initialize.py", line 71, in init_nlp
    nlp.initialize(lambda: train_corpus(nlp), sgd=optimizer)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/language.py", line 1246, in initialize
    proc.initialize(get_examples, nlp=self, **p_settings)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/pipeline/textcat.py", line 345, in initialize
    label_sample, _ = self._examples_to_truth(subbatch)
  File "/home/alexis.sanchez/.env/lib/python3.6/site-packages/spacy/pipeline/textcat.py", line 262, in _examples_to_truth
    truths[i, j] = eg.reference.cats[label]
ValueError: could not convert string to float: 'neg'
```

Am I doing something wrong?

**Comment by MVKozlov** [comment]
seems this should work
``` diff
@@ -42,7 +42,7 @@ def make_docs(data):
     for doc, label in tqdm(nlp.pipe(data, as_tuples=True), total = len(data)):

         # we need to set the (text)cat(egory) for each document
-        doc.cats["positive"] = label
+        doc.cats["positive"] = label == 'pos'

         # put them into a nice list
         docs.append(doc)
```
because imdb has 'pos' and 'neg' labels which is string and testcat want something convertable to numbers

**Comment by argiarubeo** [comment]
I got the same problem and I tried @MVKozlov solution, but I still have this error: 

ValueError: could not convert string to float: 'pos'

**Comment by MVKozlov** [comment]
@argiarubeo, seems your changes just not saved or you skip double `==`

you may try explicit conversion -  `doc.cats["positive"] = float(label == 'pos')`

**Comment by alex-eurec** [comment]
> seems this should work
> 
> ```diff
> @@ -42,7 +42,7 @@ def make_docs(data):
>      for doc, label in tqdm(nlp.pipe(data, as_tuples=True), total = len(data)):
> 
>          # we need to set the (text)cat(egory) for each document
> -        doc.cats["positive"] = label
> +        doc.cats["positive"] = label == 'pos'
> 
>          # put them into a nice list
>          docs.append(doc)
> ```
> 
> because imdb has 'pos' and 'neg' labels which is string and testcat want something convertable to numbers

Exactly that!

Thanks a lot @MVKozlov !

**Comment by argiarubeo** [comment]
Yes, it is working well, thank you @MVKozlov !! :)
